spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/v1/products/**
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/v1/orders/**
          - id: customer-service
            uri: lb://customer-service
            predicates:
              - Path=/api/v1/customers/**
           # --- OpenAPI docs routes (Swagger) ---
          - id: product-openapi
            uri: lb://PRODUCT-SERVICE
            predicates:
              - Path=/product-service/v3/api-docs/**
            filters:
              - StripPrefix=1

          - id: order-openapi
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/order-service/v3/api-docs/**
            filters:
              - StripPrefix=1

          - id: customer-openapi
            uri: lb://CUSTOMER-SERVICE
            predicates:
              - Path=/customer-service/v3/api-docs/**
            filters:
              - StripPrefix=1

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: product-service
        url: /product-service/v3/api-docs
      - name: order-service
        url: /order-service/v3/api-docs
      - name: customer-service
        url: /customer-service/v3/api-docs
