spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/shoplite_product_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

product:
  message: "Hello from product-service config (default profile 1)"
