spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/shoplite_product_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

product:
  message: "Hello from product-service config (default profile 1)"
