spring:
  application:
    name: product-service

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

product:
  message: "Hello from product-service config (default profile)"
